version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
    networks:
      - omer-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - db
      - redis
    networks:
      - omer-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - omer-network

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - omer-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email@example.com
      - PGADMIN_DEFAULT_PASSWORD=your_password
    depends_on:
      - db
    networks:
      - omer-network

networks:
  omer-network:
    driver: bridge
